#!/bin/python
import sys 
n = len(sys.argv)

import getopt, sys


# Remove 1st argument from the
# list of command line arguments
argumentList = sys.argv[1:]

# Options
options = "hl:"

# Long options
long_options = ["help", "version"]

try:
    # Parsing argument
    arguments, values = getopt.getopt(argumentList, options, long_options)
    
    # checking each argument
    for currentArgument, currentValue in arguments:

        if currentArgument in ("-h", "--help"):
            print ("Usage: gecko [ARGS], gecko [ARGS] >> file.txt \n OPTS: -h: print help, -v: version \n Gecko, the light echo utilitie developed by guy")
            
        elif currentArgument in ("-l", "--version"):
            print ("Version: Gecko 1.0 developed by guy")
            
            
except getopt.error as err:
    # output error, and return with an error code
    print (str(err))


for i in range(1, n):
    print(sys.argv[i], end = " ")


